config/routes.rb
ServerAps::Application.routes.draw do
  
  resources :external_posts

  resources :posts

  root "pages#home"
  
  get "/home", to: "pages#home", as: "home"
  
  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"
  
  namespace :admin do
    root "base#index"
    resources :users
  end
    
end

app/models/external_post.rb
class ExternalPost < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged
  
  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Use a secure password
  has_secure_password
  
  # Basic validations
  validates :username,:email, presence: true
  validates :username, length: { in: 4..10 }
  validates :username, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 4 }, on: :create
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session


  private
  def require_signin!
    if current_user.nil?
      redirect_to signin_url, alert: "Você precisa se logar."
    end
  end
  helper_method :require_signin!

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def user_signed_in?
    current_user ? true : false
  end
  helper_method :user_signed_in?

end

app/controllers/external_posts_controller.rb
class ExternalPostsController < ApplicationController
  before_action :set_external_post, only: [:show, :edit, :update, :destroy]

  def index
    @external_posts = ExternalPost.all
  end

  def show
  end

  def new
    @external_post = ExternalPost.new
  end

  def edit
  end

  def create
    @external_post = ExternalPost.new(external_post_params)

    respond_to do |format|
      if @external_post.save
        format.html { redirect_to @external_post, notice: 'Post criado.' }
        format.json { render action: 'show', status: :created, location: @external_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @external_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @external_post.update(external_post_params)
        format.html { redirect_to @external_post, notice: 'Post atualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @external_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @external_post.destroy
    respond_to do |format|
      format.html { redirect_to external_posts_url }
      format.json { head :no_content }
    end
  end

  private
    def set_external_post
      @external_post = ExternalPost.find(params[:id])
    end

    def external_post_params
      params.require(:external_post).permit(:title, :body, :published)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | ServerAps"      
    end
  end
end

app/helpers/external_posts_helper.rb
module ExternalPostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/external_posts/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for(@external_post) do |f| %>
      <% if @external_post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@external_post.errors.count, "error") %> prohibited this external_post from being saved:</h2>

          <ul>
          <% @external_post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label 'Título' %>
        <div class="row">
          <div class="col-sm-6">
            <%= f.text_field :title %>
        </div>
      </div>
    </div>

    <div class="form-group">
        <%= f.label 'Corpo' %>
        <div class="row">
          <div class="col-sm-6">
            <%= f.text_area :body %>
        </div>
      </div>
    </div>

    <div class="form-group">
        <%= f.label 'Publicado' %>
        <div class="row">
          <div class="col-sm-6">
            <%= f.check_box :published %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit 'Salvar', class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/external_posts/edit.html.erb
<h1>Editing external_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @external_post %> |
<%= link_to 'Back', external_posts_path %>

app/views/external_posts/index.html.erb
<h1>Posts</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Título</th>
      <th>Corpo</th>
      <th>Publicado</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @external_posts.each do |external_post| %>
      <tr>
        <td><%= external_post.title %></td>
        <td><%= truncate(external_post.body, :length => 150, :omission => '... (continua)')%></td>
        <td><%= external_post.published %></td>
        <td><%= link_to 'Mais', external_post %></td>
        <td><%= link_to 'Editar', edit_external_post_path(external_post) %></td>
        <td><%= link_to 'Excluir', external_post, method: :delete, data: { confirm: 'Tem certeza disso?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Post', new_external_post_path %>

app/views/external_posts/new.html.erb
<h1>Novo Post</h1>

<%= render 'form' %>

<%= link_to 'Voltar', external_posts_path %>

app/views/external_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @external_post.title %>
</p>

<p>
  <strong>Corpo:</strong>
  <%= @external_post.body %>
</p>

<p>
  <strong>Publicado:</strong>
  <%= @external_post.published %>
</p>

<%= link_to 'Editar', edit_external_post_path(@external_post) %> |
<%= link_to 'Voltar', external_posts_path %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          &copy; 2014 - APS!
          <br/>
        </small></p>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "Posts", external_posts_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "ServerAps" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      
    <div class="container">
       
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>     
      </div>  
      
    </div>
  </div>
    
  <%= render 'layouts/footer' %>    

</body>
</html>

app/views/pages/home.html.erb
<% title("Server App") %>
<h1>Bem-Vindo <small>admin</small></h1>
<p>Área de cadastro de posts.</p>